Repository WildCodeSchool/orleans-php-202009-project-sophrologie, pull requests merged in 2020-12, with the labels that each got.

#2 initialization commit
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/admin/layoutAdmin.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
Labels: Correction done, Reviewed

#3 dev to master
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/admin/layoutAdmin.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
Labels: Reviewed

#4 Fix initialisation
  .gitignore
  assets/js/app.js
  assets/styles/app.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#5 Dev to Master
  .gitignore
  assets/js/app.js
  assets/styles/app.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#36 S01_US10_navbar finish
  .gitignore
  assets/js/app.js
  assets/styles/navbar.scss
  assets/styles/variables.scss
  templates/base.html.twig
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
  webpack.config.js
Labels: Reviewed

#29 adding section2 introducing the client
  assets/images/profil.png
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
Labels: Reviewed

#30 adding section3 what is sofrolog
  assets/images/ampoule.png
  assets/images/lightbulb.png
  assets/styles/variables.scss
  templates/home/index.html.twig
Labels: Reviewed

#38 S01US07_timetable
  assets/images/contact-timetable.jpg
  assets/js/app.js
  assets/styles/contact.scss
  composer.lock
  src/Controller/ContactController.php
  templates/contact/index.html.twig
  webpack.config.js
Labels: Reviewed

#39 Fix us01
  templates/home/index.html.twig
Labels: Reviewed

#40 S01 us09 1 create admin home navbar
  assets/js/navbarAdmin.js
  assets/styles/navbarAdmin.scss
  assets/styles/variables.scss
  package.json
  src/Controller/AdminHomeController.php
  templates/admin/layoutAdmin.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#32 S01 us35 event
  assets/images/snow.jpg
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/event.scss
  composer.json
  migrations/Version20201209213134.php
  src/Controller/EventController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  src/Repository/.gitignore
  src/Repository/EventRepository.php
  templates/event/index.html.twig
  webpack.config.js
Labels: Reviewed

#42 fix us02
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  templates/home/index.html.twig
Labels: Reviewed

#43 fix_S01US07 add_fix_banner_&_css_banner
  assets/styles/contact.scss
  templates/contact/index.html.twig
Labels: Reviewed

#44 correct route event index
  src/Controller/EventController.php
Labels: Reviewed

#45 S01_11_footer finish
  .DS_Store
  .gitignore
  assets/.DS_Store
  assets/styles/footer.scss
  assets/styles/variables.scss
  templates/base.html.twig
  templates/includes/_footer.html.twig
  templates/layout.html.twig
  webpack.config.js
Labels: Reviewed

#46 suprress button en savoir plus
  templates/event/index.html.twig
Labels: Reviewed

#48 Fix css home page
  assets/styles/home.scss
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#47 fix link home
  templates/base.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
  templates/layout.html.twig
Labels: Reviewed

#49 remove button rdv
  templates/home/index.html.twig
Labels: Reviewed

#51 Fix event
  assets/styles/event.scss
  src/DataFixtures/EventFixtures.php
Labels: Reviewed

#52 Fix banner
  assets/styles/event.scss
  templates/event/index.html.twig
Labels: Reviewed

#71 adding specific text from our client
  assets/images/star.png
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#77 S02 us45 create event
  assets/js/app.js
  assets/styles/newEvent.scss
  composer.json
  composer.lock
  migrations/Version20201212190413.php
  src/Controller/AdminEventController.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  src/Form/EventType.php
  symfony.lock
  templates/admin_event/new.html.twig
  templates/layoutAdmin.html.twig
  webpack.config.js
Labels: Reviewed

#73 create entity for adding new speciality then
  assets/js/app.js
  assets/styles/specialityAdmin.scss
  config/packages/translation.yaml
  migrations/Version20201212150933.php
  src/Controller/AdminHomeController.php
  src/Controller/HomeController.php
  src/Entity/Speciality.php
  src/Form/SpecialityType.php
  src/Repository/SpecialityRepository.php
  templates/speciality/new.html.twig
  webpack.config.js
Labels: Reviewed

#81 S02 us40 index admin event
  assets/js/app.js
  assets/styles/adminList.scss
  src/Controller/AdminEventController.php
  templates/admin_event/edit.html.twig
  templates/admin_event/index.html.twig
  templates/admin_event/new.html.twig
  webpack.config.js
Labels: Reviewed

#84 S02 us37 delete event
  assets/styles/newEvent.scss
  src/Controller/AdminEventController.php
  templates/admin_event/index.html.twig
Labels: Reviewed

#86 fix the color
  assets/styles/variables.scss
Labels: Reviewed

#87 adding better styles & display new content
  assets/styles/home.scss
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: Reviewed

#90 S02 us38 event detail
  .github/workflows/main.yml
  assets/styles/event.scss
  migrations/Version20201216194754.php
  src/Controller/EventController.php
  src/DataFixtures/EventFixtures.php
  templates/event/index.html.twig
  templates/event/show.html.twig
Labels: Reviewed

#89 sizing paragraph and link elements to 20px
  assets/styles/app.scss
  composer.lock
Labels: Reviewed

#93 git commit fix regression event banner
  assets/styles/event.scss
  templates/event/index.html.twig
Labels: Reviewed

#98 dev to master
  .github/workflows/main.yml
  assets/images/star.png
  assets/js/app.js
  assets/styles/adminList.scss
  assets/styles/app.scss
  assets/styles/event.scss
  assets/styles/home.scss
  assets/styles/newEvent.scss
  assets/styles/specialityAdmin.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  config/packages/translation.yaml
  migrations/Version20201212150933.php
  migrations/Version20201212190413.php
  migrations/Version20201216194754.php
  src/Controller/AdminEventController.php
  src/Controller/AdminHomeController.php
  src/Controller/AdminSpecialityController.php
  src/Controller/EventController.php
  src/Controller/HomeController.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  src/Entity/Speciality.php
  src/Form/EventType.php
  src/Form/SpecialityType.php
  src/Repository/SpecialityRepository.php
  symfony.lock
  templates/admin/layoutAdmin.html.twig
  templates/admin_event/_form.html.twig
  templates/admin_event/edit.html.twig
  templates/admin_event/index.html.twig
  templates/admin_event/new.html.twig
  templates/event/index.html.twig
  templates/event/show.html.twig
  templates/home/index.html.twig
  templates/layoutAdmin.html.twig
  templates/speciality/edit.html.twig
  templates/speciality/indexAdmin.html.twig
  templates/speciality/new.html.twig
  webpack.config.js
Labels: Reviewed

#85 finish to display sections for the administrator to choose
  assets/images/actualite.jpg
  assets/images/seance.jpg
  assets/images/specialite.png
  assets/images/temoignage.png
  assets/js/app.js
  assets/styles/adminHome.scss
  src/Controller/AdminHomeController.php
  templates/admin/index.html.twig
  webpack.config.js
Labels: Correction done, Reviewed

#99 removeDSStore
  .DS_Store
  .gitignore
  assets/.DS_Store
Labels: Reviewed

#100 delete exceeded navbar and add link on the navbar
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#101 dev to master
  .DS_Store
  .env
  .github/workflows/main.yml
  .gitignore
  assets/.DS_Store
  assets/images/actualite.jpg
  assets/images/phone-contact.jpg
  assets/images/seance.jpg
  assets/images/specialite.png
  assets/images/temoignage.png
  assets/js/app.js
  assets/styles/adminHome.scss
  assets/styles/contact.scss
  config/services.yaml
  migrations/Version20201217201645.php
  src/Controller/AdminHomeController.php
  src/Controller/AdminSpecialityController.php
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  src/Repository/ContactRepository.php
  templates/admin/index.html.twig
  templates/contact/index.html.twig
  templates/contact/mail.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
  templates/speciality/_delete.html.twig
  webpack.config.js
Labels: Reviewed

#103 supress column, modify buttons
  assets/styles/adminList.scss
  templates/admin_event/index.html.twig
Labels: Reviewed

#102 fix redirect route | changing font
  assets/styles/specialityAdmin.scss
  templates/speciality/indexAdmin.html.twig
Labels: Reviewed

#88 fix_section_timetable_style
  .github/workflows/main.yml
  assets/styles/contact.scss
  templates/contact/index.html.twig
Labels: Correction done, Reviewed

#124 second_fix_new_style_timetable_section
  assets/styles/contact.scss
  templates/contact/index.html.twig
Labels: Reviewed

#128 S03US08_map_&_informations_contact
  assets/styles/contact.scss
  templates/contact/index.html.twig
Labels: Reviewed

#125 fix choice category on form
  migrations/Version20201216194754.php
  migrations/Version20201223172100.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Category.php
  src/Entity/Event.php
  src/Form/EventType.php
  src/Repository/CategoryRepository.php
  templates/admin_event/index.html.twig
  templates/event/index.html.twig
Labels: Reviewed

#129 S03US20_sophrology_presentation
  assets/images/sophrology-presentation.jpg
  assets/styles/sophrology.scss
  src/Controller/SophrologyController.php
  templates/sophrology/index.html.twig
  webpack.config.js
Labels: Correction done
