Repository WildCodeSchool/orleans-php-202009-project-sophrologie, pull requests merged in 2021-01, with the labels that each got.

#130 S03 us54 archive event list with fix entity category
  assets/styles/contact.scss
  migrations/Version20201217201645.php
  migrations/Version20201222091019.php
  src/Controller/AdminEventController.php
  src/Controller/EventController.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  src/Form/EventType.php
  templates/admin_event/index.html.twig
  templates/event/index.html.twig
  templates/event/show.html.twig
Labels: Reviewed

#132 S03US19_add_section_sophrology_help
  assets/styles/sophrology.scss
  templates/sophrology/index.html.twig
Labels: Reviewed

#134 S03 us53 event filter client
  src/Controller/AdminEventController.php
  src/Controller/EventController.php
  src/Form/EventType.php
  src/Form/SearchEventFormType.php
  templates/admin_event/index.html.twig
  templates/event/index.html.twig
Labels: Reviewed

#135 fix_css_client_color
  assets/images/accueil.jpg
  assets/images/logo.png
  assets/images/snow.jpg
  assets/styles/adminHome.scss
  assets/styles/adminList.scss
  assets/styles/app.scss
  assets/styles/contact.scss
  assets/styles/event.scss
  assets/styles/footer.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/newEvent.scss
  assets/styles/sophrology.scss
  assets/styles/specialityAdmin.scss
  assets/styles/variables.scss
  templates/contact/index.html.twig
  templates/event/index.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
  templates/sophrology/index.html.twig
Labels: Reviewed

#136 fix route
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#139 adding btn log(in/out)
  assets/styles/footer.scss
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
Labels: Reviewed

#141 add_link_page_sophrology
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
Labels: Reviewed

#144 S03 us52 wysiwyg
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  src/Form/EventType.php
  symfony.lock
  templates/event/show.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#145 fix_style_and_color_sophrology_page
  assets/styles/sophrology.scss
  templates/sophrology/index.html.twig
Labels: Reviewed

#142 add_links_footer_and_one_link_navbar
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
Labels: Correction done, Reviewed

#148 Fix admin edit speciality and event
  assets/styles/newEvent.scss
  assets/styles/specialityAdmin.scss
  templates/admin_event/edit.html.twig
  templates/speciality/edit.html.twig
Labels: Reviewed

#133 S03 us25 detailsseanceindividuel
  assets/images/pin.png
  assets/styles/seances.scss
  assets/styles/variables.scss
  src/Controller/SeancesController.php
  templates/seances/index.html.twig
  webpack.config.js
Labels: Reviewed

#143 change_color_contact_page_and_add_jumbotron_style
  assets/styles/contact.scss
  assets/styles/variables.scss
  migrations/Version20210106082902.php
  templates/contact/index.html.twig
Labels: Changes requested

#151 fix link navbar, footer and change css
  assets/styles/footer.scss
  assets/styles/variables.scss
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
Labels: Reviewed

#150 Fix police button
  assets/styles/variables.scss
  templates/contact/index.html.twig
  templates/event/show.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#152 harmonize speciality card like on other page
  assets/styles/home.scss
  assets/styles/navbarAdmin.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
Labels: Reviewed

#154 add_image_office_and_change_style_section_map
  assets/images/office.jpg
  symfony.lock
  templates/contact/index.html.twig
Labels: Reviewed

#155 fix color button edit and archive
  templates/admin_event/index.html.twig
  templates/speciality/indexAdmin.html.twig
Labels: Reviewed

#156 Fix event layout
  assets/styles/app.scss
  assets/styles/event.scss
  src/Form/SearchEventFormType.php
  templates/event/index.html.twig
Labels: Reviewed

#159 add missing endblock endfile
  templates/contact/index.html.twig
Labels: Reviewed

#158 S04US21_add_section_sophrology_who
  assets/styles/sophrology.scss
  templates/sophrology/index.html.twig
Labels: Reviewed

#157 changing navbar admin style
  assets/images/worker.png
  assets/js/app.js
  assets/js/navbarAdmin.js
  assets/styles/adminHome.scss
  assets/styles/navbarAdmin.scss
  templates/itemAdmin/_navbarAdmin.html.twig
  templates/layout.html.twig
  webpack.config.js
Labels: Reviewed

#160 Dev -> master for review
  assets/images/office.jpg
  assets/images/worker.png
  assets/js/app.js
  assets/js/navbarAdmin.js
  assets/styles/adminHome.scss
  assets/styles/app.scss
  assets/styles/event.scss
  assets/styles/navbarAdmin.scss
  assets/styles/sophrology.scss
  src/Form/SearchEventFormType.php
  symfony.lock
  templates/admin_event/index.html.twig
  templates/contact/index.html.twig
  templates/event/index.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
  templates/layout.html.twig
  templates/sophrology/index.html.twig
  templates/speciality/indexAdmin.html.twig
  webpack.config.js
Labels: Reviewed

#166 fix home page style
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#167 fix sophro page style
  assets/styles/sophrology.scss
  templates/sophrology/index.html.twig
Labels: Reviewed

#169 changing police and size
  assets/styles/footer.scss
  assets/styles/variables.scss
  templates/includes/_footer.html.twig
Labels: Reviewed

#171 changing bg image position / moving btn position
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#173 create controller to sign in and a view for that
  composer.lock
  migrations/Version20210105192717.php
  migrations/Version20210106082902.php
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: Reviewed

#178 S04US65_create_faq_page_scss_link_footer_and_create_entity
  assets/styles/faq.scss
  src/Controller/FaqController.php
  src/Entity/Faq.php
  src/Repository/FaqRepository.php
  templates/faq/index.html.twig
  templates/includes/_footer.html.twig
  webpack.config.js
Labels: Reviewed

#170 Fix navbar
  assets/styles/app.scss
  assets/styles/navbar.scss
  package.json
  templates/includes/_navbar.html.twig
  yarn.lock
Labels: Reviewed

#172 add the typehint for property in User entity
  config/packages/security.yaml
  migrations/Version20210111124233.php
  src/Controller/AdminUser.php
  src/Entity/User.php
  templates/user/account.html.twig
Labels: Reviewed

#187 S03 us45 fixtures tesyimony crud
  composer.json
  composer.lock
  src/DataFixtures/TestimonyFixtures.php
Labels: Reviewed

#193 S04US66_crud_add_faq
  migrations/Version20210118082600.php
  src/Controller/AdminFaqController.php
  src/Controller/FaqController.php
  src/DataFixtures/FaqFixtures.php
  src/Form/FaqType.php
  templates/admin_faq/indexAdmin.html.twig
  templates/admin_faq/new.html.twig
Labels: Reviewed

#188 Fix user fixtures
  assets/images/user-solid.svg
  migrations/Version20210106130319.php
  migrations/Version20210118092321.php
  src/DataFixtures/UserFixtures.php
Labels: Correction done, Reviewed

#181 S04 us41 upload
  .gitignore
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/event.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210118095822.php
  package.json
  public/uploads/2020-12-26-5ff9aa9777437267975560.jpg
  public/uploads/2020-12-26-5ff9af61756e9203871452.jpg
  public/uploads/chat1-5ff99ca51bf2e398045193.jpg
  public/uploads/parson-5ff9e617c771f247729647.jpg
  public/uploads/parson-5ff9f7810b91a826510925.jpg
  public/uploads/parson.jpg
  public/uploads/tbbt.jpeg
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  src/Form/EventType.php
  symfony.lock
  templates/event/index.html.twig
  templates/event/show.html.twig
  yarn.lock
Labels: Correction done, Reviewed

#197 S04US67_crud_update_faq_view_edit
  src/Controller/AdminFaqController.php
  templates/admin_faq/edit.html.twig
  templates/admin_faq/indexAdmin.html.twig
Labels: Reviewed

#201 S04_US30_updateTarif
  src/Controller/AdminPriceController.php
  src/Entity/Price.php
  src/Form/PriceType.php
  templates/admin_price/edit.html.twig
  templates/admin_price/index.html.twig
Labels: Reviewed

#202 S04 us64 video detail event
  src/DataFixtures/EventFixtures.php
  templates/event/show.html.twig
Labels: Reviewed

#205 fix migration
  migrations/Version20210111124233.php
  migrations/Version20210112201842.php
  migrations/Version20210118082600.php
  migrations/Version20210118092321.php
  migrations/Version20210118155402.php
Labels: Reviewed

#203 create link to redirect user
  src/Controller/AdminHomeController.php
  src/Controller/AdminUser.php
  src/Security/LoginFormAuthenticator.php
  templates/includes/_navbar.html.twig
Labels: Correction done, Reviewed

#206 S04US68_crud_delete_faq_link
  src/Controller/AdminFaqController.php
  templates/admin_faq/_delete.html.twig
  templates/admin_faq/indexAdmin.html.twig
Labels: Reviewed

#207 S04_US31_deleteTarif
  src/Controller/AdminPriceController.php
  templates/admin_price/index.html.twig
Labels: Reviewed

#208 add flash on old CRUD
  src/Controller/AdminEventController.php
  src/Controller/AdminSpecialityController.php
  templates/base.html.twig
Labels: Reviewed

#209 font site text
  assets/styles/variables.scss
Labels: Reviewed

#216 fix_S04US66_style_FAQ
  assets/images/compass.jpg
  assets/styles/faq.scss
  src/Controller/FaqController.php
  src/DataFixtures/FaqFixtures.php
  templates/faq/index.html.twig
Labels: Reviewed

#183 CRUD part read
  templates/testimony/_form.html.twig
  templates/testimony/index.html.twig
  templates/testimony/show.html.twig
Labels: Correction done, Reviewed

#200 put text in french
  templates/testimony/_delete_form.html.twig
Labels: Correction done, Reviewed

#220 S04US28 card tarif
  assets/styles/seances.scss
  src/Controller/SeancesController.php
  templates/price/show.html.twig
  templates/seances/index.html.twig
Labels: Reviewed

#204 adding edit form for user in personnal page
  src/Controller/AdminUser.php
  src/Form/UserType.php
  templates/user/account.html.twig
Labels: Reviewed

#213 fix message flash on edit and delete
  src/Controller/AdminPriceController.php
Labels: Correction done, Reviewed

#218 test sent message
  migrations/Version20210118155402.php
  migrations/Version20210119191016.php
  src/Controller/AdminReportController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Report.php
  src/Entity/User.php
  src/Form/ReportType.php
  src/Repository/ReportRepository.php
  templates/admin_report/index.html.twig
Labels: Reviewed

#224 adding logo user and fixing layout
  assets/images/user.png
  assets/styles/navbar.scss
  templates/includes/_navbar.html.twig
Labels: Reviewed

#225 hover_effect_sophrology
  assets/images/briefcase.png
  assets/images/couple.png
  assets/images/daughter.png
  assets/images/motherhood.png
  assets/images/son.png
  assets/styles/sophrology.scss
  templates/sophrology/index.html.twig
Labels: Reviewed

#227 Fix speciality fixtures
  src/DataFixtures/SpecialityFixtures.php
  src/Entity/Speciality.php
Labels: Reviewed

#228 layout event show
  assets/styles/event.scss
  templates/event/index.html.twig
  templates/event/show.html.twig
Labels: Reviewed

#229 fix form event wrong labels
  src/Form/EventType.php
Labels: Reviewed

#226 put style form
  src/Form/TestimonyType.php
  templates/testimony/_form.html.twig
  templates/testimony/edit.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
Labels: Reviewed

#233 fix_link_faq_admin
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#230 S04_US22 CollectiveSession
  assets/images/seanceCollective.jpeg
  assets/images/sophro-entreprise.jpg
  assets/styles/collectiveSessions.scss
  src/Controller/CollectiveSessionController.php
  templates/collective_session/index.html.twig
  templates/includes/_navbar.html.twig
  webpack.config.js
Labels: Reviewed

#231 fix fixture role user
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#222 Fix homepage image
  assets/images/pissenlits.jpg
  assets/styles/home.scss
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
Labels: Correction done, Reviewed

#234 fix database
  migrations/Version20210119191016.php
  migrations/Version20210121145504.php
Labels: Reviewed

#223 changing layout, similar to navbar client
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#235 fix button category event
  src/Form/SearchEventFormType.php
  templates/event/index.html.twig
Labels: Reviewed

#237 fix button rv link
  templates/collective_session/index.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/seances/index.html.twig
Labels: Reviewed

#239 fix navbar and maj link footer
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
Labels: Reviewed

#242 fix_link_and_style_sophro_page
  assets/images/sophrology-presentation.jpg
  assets/images/waterfalls.jpg
  assets/images/waterfalls.png
  assets/styles/sophrology.scss
  templates/sophrology/index.html.twig
Labels: Reviewed

#210 S04 us65 search function
  src/Controller/AdminEventController.php
  src/Entity/EventSearch.php
  src/Form/SearchAdminEventType.php
  src/Repository/EventRepository.php
  templates/admin_event/index.html.twig
Labels: Reviewed

#243 S03 s44 view testimony
  assets/styles/seances.scss
  src/Controller/SeancesController.php
  templates/seances/index.html.twig
Labels: Reviewed

#238 fix_contact_page_style_image
  assets/images/contact-timetable.jpg
  assets/images/contact.jpg
  assets/images/office.jpg
  assets/images/office.png
  assets/images/phone-contact.jpg
  assets/styles/contact.scss
  templates/contact/index.html.twig
Labels: Reviewed

#240 S04us70 bis display reports
  assets/styles/myAccount.scss
  composer.lock
  src/Controller/AdminReportController.php
  src/Controller/AdminUser.php
  templates/user/account.html.twig
  webpack.config.js
Labels: Reviewed

#241 S04 us72 add logo
  migrations/Version20210121215045.php
  src/Controller/AdminLogoController.php
  src/Entity/Logo.php
  src/Form/LogoType.php
  src/Repository/LogoRepository.php
  templates/admin_logo/_delete_form.html.twig
  templates/admin_logo/_form.html.twig
  templates/admin_logo/edit.html.twig
  templates/admin_logo/index.html.twig
  templates/admin_logo/new.html.twig
  templates/admin_logo/show.html.twig
Labels: Correction done, Reviewed

#246 Fix cards price section
  templates/price/show.html.twig
  templates/seances/index.html.twig
Labels: Reviewed

#248 add link navbar and fix admin price
  templates/admin_price/edit.html.twig
  templates/admin_price/index.html.twig
  templates/admin_price/new.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#249 udapte name link
  templates/includes/_footer.html.twig
Labels: Reviewed

#250 add champ in index, update layout and add button
  templates/speciality/edit.html.twig
  templates/speciality/indexAdmin.html.twig
  templates/speciality/new.html.twig
Labels: Reviewed

#251 fix_flash_alert_translate_label_and_fix_index_faq
  src/Controller/AdminFaqController.php
  src/Form/FaqType.php
  templates/admin_faq/indexAdmin.html.twig
Labels: Reviewed

#247 S04 us72 index logo
  src/Controller/AdminLogoController.php
  src/DataFixtures/LogoFixtures.php
  templates/admin_logo/index.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#252 adjusting layout homepage w/ tag p. adding new link register to navbar
  assets/styles/home.scss
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
Labels: Reviewed

#254 modify speciality entity and label form
  migrations/Version20210122175501.php
  src/DataFixtures/SpecialityFixtures.php
  src/Entity/Speciality.php
  src/Form/SpecialityType.php
  templates/speciality/indexAdmin.html.twig
Labels: Reviewed

#255 harmonize button return index admin
  assets/styles/adminList.scss
  assets/styles/faq.scss
  templates/admin_event/index.html.twig
  templates/admin_faq/indexAdmin.html.twig
  templates/admin_price/index.html.twig
  templates/speciality/indexAdmin.html.twig
  templates/testimony/index.html.twig
Labels: Reviewed

#256 S04 us73 edit logo
  src/Controller/AdminLogoController.php
  templates/admin_logo/edit.html.twig
  templates/admin_logo/index.html.twig
  templates/admin_logo/new.html.twig
  templates/admin_logo/show.html.twig
Labels: Reviewed

#257 bg event, size form search
  assets/styles/event.scss
  templates/event/index.html.twig
Labels: Reviewed

#258 add home text presentation
  templates/home/index.html.twig
Labels: Correction done, Reviewed

#259 Fix home layout speciality
  assets/styles/home.scss
  src/DataFixtures/SpecialityFixtures.php
  templates/home/index.html.twig
Labels: Reviewed

#260 S04 us74 delete logo
  src/Controller/AdminLogoController.php
  templates/admin_logo/index.html.twig
Labels: Reviewed

#262 fix_contact_request_client
  assets/images/contact.jpg
  assets/styles/contact.scss
  templates/contact/index.html.twig
Labels: Reviewed

#253 Fix reports admin option select
  migrations/Version20210122160402.php
  src/Entity/Report.php
  src/Entity/User.php
  src/Form/ReportType.php
  templates/admin_report/index.html.twig
  templates/user/account.html.twig
Labels: Reviewed

#263 fix_icons_statements_sophrology
  assets/styles/sophrology.scss
  templates/sophrology/index.html.twig
Labels: Reviewed

#264 Add wysiwig on speciality
  assets/styles/home.scss
  composer.lock
  src/Form/SpecialityType.php
  templates/home/index.html.twig
Labels: Reviewed

#265 fix_route_french_admin_templates
  src/Controller/AdminEventController.php
  src/Controller/AdminFaqController.php
  src/Controller/AdminLogoController.php
  src/Controller/AdminPriceController.php
  src/Controller/AdminReportController.php
  src/Controller/AdminSpecialityController.php
  src/Controller/CollectiveSessionController.php
  src/Controller/EventController.php
  src/Controller/RegistrationController.php
  src/Controller/SophrologyController.php
  src/Controller/TestimonyController.php
Labels: Reviewed

#266 fix affichage indexs admin
  templates/admin_event/index.html.twig
  templates/admin_logo/index.html.twig
  templates/admin_price/index.html.twig
  templates/speciality/indexAdmin.html.twig
Labels: Reviewed

#267 fix_words_statements_contact_request_client
  templates/contact/index.html.twig
Labels: Reviewed

#261 S05 us75 upload logo
  assets/styles/adminList.scss
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210122152758.php
  src/DataFixtures/LogoFixtures.php
  src/Entity/Event.php
  src/Entity/Logo.php
  src/Form/LogoType.php
  templates/admin_event/index.html.twig
  templates/admin_logo/index.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#268 update alone session
  assets/styles/seances.scss
  assets/styles/variables.scss
  templates/seances/index.html.twig
Labels: Reviewed

#269 Us user filter for admin reports
  src/Controller/AdminReportController.php
  src/Entity/SearchAdminReports.php
  src/Form/SearchAdminReportsType.php
  src/Repository/ReportRepository.php
  templates/admin_report/index.html.twig
Labels: Reviewed

#270 link admin home
  assets/images/handup.jpg
  assets/images/report.jpg
  assets/images/sphere.jpg
  assets/styles/adminHome.scss
  templates/admin/index.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#271 better stylish like navbar client
  assets/styles/navbarAdmin.scss
  templates/includes/_navbar.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#273 Fix search bar admin event
  assets/styles/adminList.scss
  src/Form/SearchAdminEventType.php
  templates/admin_event/index.html.twig
Labels: Reviewed

#274 fix speciality police with p
  templates/home/index.html.twig
Labels: Reviewed

#275 fix cards
  assets/styles/collectiveSessions.scss
  templates/collective_session/index.html.twig
Labels: Reviewed

#276 Favicon
  assets/images/favicon.png
Labels: Reviewed

#279 fix_tex_sophrology
  templates/sophrology/index.html.twig
Labels: Reviewed

#277 fix text homepage
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#272 S05 us77 layout logo seance
  src/Controller/CollectiveSessionController.php
  src/DataFixtures/LogoFixtures.php
  templates/collective_session/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#278 fix_style_events-page
  assets/styles/event.scss
  templates/event/index.html.twig
Labels: Reviewed

#280 add logo, link social network and update margin
  templates/includes/_footer.html.twig
Labels: Reviewed

#282 fix tex price and seance
  templates/seances/index.html.twig
Labels: Reviewed

#283 add link event in collective
  templates/collective_session/index.html.twig
Labels: Reviewed

#285 fix spelling
  templates/event/index.html.twig
Labels: Reviewed

#286 dev to master
  templates/collective_session/index.html.twig
  templates/event/index.html.twig
  templates/seances/index.html.twig
Labels: Reviewed

#288 add_legal_notice
  assets/styles/mention.scss
  src/Controller/LegalNoticeController.php
  templates/includes/_footer.html.twig
  templates/mention/index.html.twig
  webpack.config.js
Labels: Reviewed

#287 create 404 and 500 error pages
  assets/images/dandelion.png
  assets/styles/home.scss
  composer.lock
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/includes/_footer.html.twig
Labels: Reviewed

#284 S04 us76 password reinitialisation
  assets/styles/login.scss
  assets/styles/request.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  config/services.yaml
  migrations/Version20210125050926.php
  phpstan.neon
  src/Controller/ResetPasswordController.php
  src/Controller/SecurityController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  webpack.config.js
Labels: Reviewed

#289 dev to master
  assets/images/dandelion.png
  assets/styles/home.scss
  assets/styles/login.scss
  assets/styles/mention.scss
  assets/styles/request.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  config/services.yaml
  migrations/Version20210125050926.php
  phpstan.neon
  src/Controller/LegalNoticeController.php
  src/Controller/ResetPasswordController.php
  src/Controller/SecurityController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/includes/_footer.html.twig
  templates/mention/index.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  webpack.config.js
Labels: Reviewed

#292 add_readme
  Readme.md
Labels: Reviewed

#290 fix button
  templates/collective_session/index.html.twig
Labels: Reviewed

#291 fix_title_page_add_readme
  templates/admin/index.html.twig
  templates/admin_event/edit.html.twig
  templates/admin_event/new.html.twig
  templates/admin_faq/edit.html.twig
  templates/admin_faq/indexAdmin.html.twig
  templates/admin_faq/new.html.twig
  templates/admin_logo/edit.html.twig
  templates/admin_logo/new.html.twig
  templates/admin_price/edit.html.twig
  templates/admin_price/new.html.twig
  templates/admin_report/index.html.twig
  templates/collective_session/index.html.twig
  templates/contact/index.html.twig
  templates/faq/index.html.twig
  templates/layoutAdmin.html.twig
  templates/mention/index.html.twig
  templates/registration/register.html.twig
  templates/reset_password/check_email.html.twig
  templates/seances/index.html.twig
  templates/security/login.html.twig
  templates/sophrology/index.html.twig
  templates/speciality/edit.html.twig
  templates/speciality/indexAdmin.html.twig
  templates/speciality/new.html.twig
  templates/testimony/edit.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
  templates/testimony/show.html.twig
Labels: Reviewed

#294 Fix message flash
  src/Controller/TestimonyController.php
Labels: Reviewed

#295 changing padding margin and layout
  assets/styles/app.scss
  templates/home/index.html.twig
Labels: Reviewed

#299 fix button return home
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#296 changing padding margin
  templates/sophrology/index.html.twig
Labels: Reviewed

#298 chaging padding margin n layout
  templates/seances/index.html.twig
Labels: Reviewed

#293 done 401 error page
  templates/bundles/TwigBundle/Exception/error401.html.twig
Labels: Reviewed

#297 spelling_reading
  templates/collective_session/index.html.twig
  templates/home/index.html.twig
  templates/seances/index.html.twig
  templates/sophrology/index.html.twig
Labels: Correction done, Reviewed

#300 dev to master
  Readme.md
  assets/styles/app.scss
  src/Controller/TestimonyController.php
  templates/admin/index.html.twig
  templates/admin_event/edit.html.twig
  templates/admin_event/new.html.twig
  templates/admin_faq/edit.html.twig
  templates/admin_faq/indexAdmin.html.twig
  templates/admin_faq/new.html.twig
  templates/admin_logo/edit.html.twig
  templates/admin_logo/new.html.twig
  templates/admin_price/edit.html.twig
  templates/admin_price/new.html.twig
  templates/admin_report/index.html.twig
  templates/bundles/TwigBundle/Exception/error401.html.twig
  templates/collective_session/index.html.twig
  templates/contact/index.html.twig
  templates/faq/index.html.twig
  templates/home/index.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
  templates/layoutAdmin.html.twig
  templates/mention/index.html.twig
  templates/registration/register.html.twig
  templates/reset_password/check_email.html.twig
  templates/seances/index.html.twig
  templates/security/login.html.twig
  templates/sophrology/index.html.twig
  templates/speciality/edit.html.twig
  templates/speciality/indexAdmin.html.twig
  templates/speciality/new.html.twig
  templates/testimony/edit.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
  templates/testimony/show.html.twig
Labels: Reviewed

#342 Fix assert logo
  src/Entity/Logo.php
Labels: Reviewed

#343 fix text event
  templates/event/index.html.twig
Labels: Reviewed

#344 fix issue 322, balises dans tableau police sans balises
  assets/styles/specialityAdmin.scss
  assets/styles/variables.scss
  templates/speciality/indexAdmin.html.twig
Labels: Reviewed

#345 add message archive
  src/Controller/AdminEventController.php
  templates/admin_event/index.html.twig
Labels: Reviewed

#347 Fix navbar logo
  assets/styles/navbar.scss
  assets/styles/navbarAdmin.scss
  templates/includes/_navbar.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#354 fix_contact_redirection_input_placeholder
  src/Controller/ContactController.php
  src/Form/ContactType.php
  templates/contact/index.html.twig
Labels: Reviewed

#348 Fix admin homepage
  assets/styles/adminHome.scss
  templates/admin/index.html.twig
Labels: Reviewed

#350 issue 323 modif text supression spécialité
  templates/speciality/_delete.html.twig
Labels: Reviewed

#351 fix placeholder and label tarif
  src/Form/PriceType.php
Labels: Reviewed

#352 fix issue 332 testimony
  src/Form/TestimonyType.php
Labels: Reviewed

#353 fix transition social network
  assets/styles/footer.scss
Labels: Reviewed

#349 Fix speciality card
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Correction done, Reviewed

#355 fix issue 310 339
  assets/styles/event.scss
  assets/styles/variables.scss
  templates/event/index.html.twig
Labels: Reviewed

#356 fix margin
  assets/styles/collectiveSessions.scss
  templates/collective_session/index.html.twig
Labels: Reviewed

#357 fix margin and transition cards price
  assets/styles/seances.scss
  templates/seances/index.html.twig
Labels: Reviewed

#359 fix responsive navbar admin
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#358 Fix sophrology photo alignement
  templates/sophrology/index.html.twig
Labels: Reviewed

#360 fix link , responsive cards and picture
  templates/collective_session/index.html.twig
Labels: Reviewed

#361 Fix supp 332 unarchive ko
  assets/styles/specialityAdmin.scss
  templates/admin_event/_delete.html.twig
  templates/admin_event/_unarchive.html.twig
  templates/admin_event/index.html.twig
  templates/admin_price/_delete.html.twig
  templates/speciality/indexAdmin.html.twig
  templates/testimony/_delete_form.html.twig
Labels: Reviewed

#362 Fix navbar admin
  templates/includes/_navbar.html.twig
  templates/itemAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#364 Fix migration
  migrations/Version20210127075544.php
  src/Form/EventType.php
Labels: Reviewed

#365 fix tableau price
  templates/admin_price/index.html.twig
Labels: Reviewed

#366 fix negative age, display lastname in testimony and take off require …
  src/Entity/Testimony.php
  src/Form/TestimonyType.php
  templates/seances/index.html.twig
Labels: Reviewed

#367 fix_margin_contactType
  src/Form/ContactType.php
Labels: Reviewed
